-- MySQL Script generated by MySQL Workbench
-- Sat Mar 30 16:37:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Clinica_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Clinica_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clinica_bd` DEFAULT CHARACTER SET utf8 ;
USE `Clinica_bd` ;

-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_procedimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_procedimiento` (
  `id_procedimiento` INT NOT NULL,
  `tipo_procedimiento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_procedimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_paciente` (
  `id_paciente` INT NOT NULL,
  `nombre_paciente` VARCHAR(45) NULL,
  `apellido_paciente` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `tb_procedimiento_id_procedimiento` INT NOT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `fk_tb_paciente_tb_procedimiento1_idx` (`tb_procedimiento_id_procedimiento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_paciente_tb_procedimiento1`
    FOREIGN KEY (`tb_procedimiento_id_procedimiento`)
    REFERENCES `Clinica_bd`.`tb_procedimiento` (`id_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`factura` (
  `id_factura` INT NOT NULL,
  `fecha` DATE NULL,
  `valor_total` VARCHAR(45) NULL,
  `tb_paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_factura_tb_paciente_idx` (`tb_paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_tb_paciente`
    FOREIGN KEY (`tb_paciente_id_paciente`)
    REFERENCES `Clinica_bd`.`tb_paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`telefono_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`telefono_paciente` (
  `telefono` VARCHAR(45) NOT NULL,
  `tb_paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`tb_paciente_id_paciente`),
  INDEX `fk_telefono_paciente_tb_paciente1_idx` (`tb_paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_telefono_paciente_tb_paciente1`
    FOREIGN KEY (`tb_paciente_id_paciente`)
    REFERENCES `Clinica_bd`.`tb_paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_medicamento` (
  `id_medicamento` INT NOT NULL,
  `nombre_medicamento` VARCHAR(45) NULL,
  `dosis` VARCHAR(45) NULL,
  `tb_medicamentocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_paciente_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_paciente_medicamento` (
  `id_paciente_medicamento` INT NOT NULL,
  `tb_medicamento_id_medicamento` INT NOT NULL,
  `tb_paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_paciente_medicamento`),
  INDEX `fk_tb_paciente_medicamento_tb_medicamento1_idx` (`tb_medicamento_id_medicamento` ASC) VISIBLE,
  INDEX `fk_tb_paciente_medicamento_tb_paciente1_idx` (`tb_paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_paciente_medicamento_tb_medicamento1`
    FOREIGN KEY (`tb_medicamento_id_medicamento`)
    REFERENCES `Clinica_bd`.`tb_medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_paciente_medicamento_tb_paciente1`
    FOREIGN KEY (`tb_paciente_id_paciente`)
    REFERENCES `Clinica_bd`.`tb_paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_medico` (
  `id_medico` INT NOT NULL,
  `nombre_medico` VARCHAR(45) NULL,
  `apellido_medico` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_medico_procedimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_medico_procedimiento` (
  `id_medico_procedimiento` INT NOT NULL,
  `tb_procedimiento_id_procedimiento` INT NOT NULL,
  `tb_medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_medico_procedimiento`),
  INDEX `fk_tb_medico_procedimiento_tb_procedimiento1_idx` (`tb_procedimiento_id_procedimiento` ASC) VISIBLE,
  INDEX `fk_tb_medico_procedimiento_tb_medico1_idx` (`tb_medico_id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_tb_medico_procedimiento_tb_procedimiento1`
    FOREIGN KEY (`tb_procedimiento_id_procedimiento`)
    REFERENCES `Clinica_bd`.`tb_procedimiento` (`id_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_medico_procedimiento_tb_medico1`
    FOREIGN KEY (`tb_medico_id_medico`)
    REFERENCES `Clinica_bd`.`tb_medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`tb_enfermero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`tb_enfermero` (
  `id_enfermero` INT NOT NULL,
  `nombre_enfermero` VARCHAR(45) NULL,
  `apellido_enfermero` VARCHAR(45) NULL,
  `tb_medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_enfermero`),
  INDEX `fk_tb_enfermero_tb_medico1_idx` (`tb_medico_id_medico` ASC) VISIBLE,
  CONSTRAINT `fk_tb_enfermero_tb_medico1`
    FOREIGN KEY (`tb_medico_id_medico`)
    REFERENCES `Clinica_bd`.`tb_medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`telefono_enfermero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`telefono_enfermero` (
  `telefono` VARCHAR(45) NOT NULL,
  `tb_enfermero_id_enfermero` INT NOT NULL,
  INDEX `fk_telefono_enfermero_tb_enfermero1_idx` (`tb_enfermero_id_enfermero` ASC) VISIBLE,
  PRIMARY KEY (`tb_enfermero_id_enfermero`),
  CONSTRAINT `fk_telefono_enfermero_tb_enfermero1`
    FOREIGN KEY (`tb_enfermero_id_enfermero`)
    REFERENCES `Clinica_bd`.`tb_enfermero` (`id_enfermero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica_bd`.`telefono_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica_bd`.`telefono_medico` (
  `telefono` VARCHAR(45) NOT NULL,
  `tb_medico_id_medico` INT NOT NULL,
  INDEX `fk_telefono_medico_tb_medico1_idx` (`tb_medico_id_medico` ASC) VISIBLE,
  PRIMARY KEY (`tb_medico_id_medico`),
  CONSTRAINT `fk_telefono_medico_tb_medico1`
    FOREIGN KEY (`tb_medico_id_medico`)
    REFERENCES `Clinica_bd`.`tb_medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
