-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 13:42:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hospital_db` ;

-- -----------------------------------------------------
-- Table `hospital_db`.`tb_procedimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`tb_procedimiento` (
  `id_procedimiento` INT NOT NULL,
  `tipo_procedimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_procedimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`tb_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`tb_paciente` (
  `id_paciente` INT NOT NULL,
  `nombre_paciente` VARCHAR(45) NOT NULL,
  `apellido_paciente` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(50) NOT NULL,
  `tb_procedimiento_id_procedimiento` INT NOT NULL,
  PRIMARY KEY (`id_paciente`, `tb_procedimiento_id_procedimiento`),
  INDEX `fk_tb_paciente_tb_procedimiento1_idx` (`tb_procedimiento_id_procedimiento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_paciente_tb_procedimiento1`
    FOREIGN KEY (`tb_procedimiento_id_procedimiento`)
    REFERENCES `hospital_db`.`tb_procedimiento` (`id_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`tb_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`tb_factura` (
  `id_factura` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `valor_total` DECIMAL(9,3) NOT NULL,
  `tb_paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_factura`, `tb_paciente_id_paciente`),
  INDEX `fk_tb_factura_tb_paciente_idx` (`tb_paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_factura_tb_paciente`
    FOREIGN KEY (`tb_paciente_id_paciente`)
    REFERENCES `hospital_db`.`tb_paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`tb_médico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`tb_médico` (
  `id_médico` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_médico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`tb_enfermero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`tb_enfermero` (
  `id_enfermero` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `tb_médico_id_médico` INT NOT NULL,
  PRIMARY KEY (`id_enfermero`),
  INDEX `fk_tb_enfermero_tb_médico1_idx` (`tb_médico_id_médico` ASC) VISIBLE,
  CONSTRAINT `fk_tb_enfermero_tb_médico1`
    FOREIGN KEY (`tb_médico_id_médico`)
    REFERENCES `hospital_db`.`tb_médico` (`id_médico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`teléfono_enfermero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`teléfono_enfermero` (
  `teléfono` INT NOT NULL,
  `tb_enfermero_id_enfermero` INT NOT NULL,
  PRIMARY KEY (`tb_enfermero_id_enfermero`),
  CONSTRAINT `fk_teléfono_enfermero_tb_enfermero1`
    FOREIGN KEY (`tb_enfermero_id_enfermero`)
    REFERENCES `hospital_db`.`tb_enfermero` (`id_enfermero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`médico_procedimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`médico_procedimiento` (
  `id_médico_procedimiento` INT NOT NULL,
  `tb_procedimiento_id_procedimiento` INT NOT NULL,
  `tb_médico_id_médico` INT NOT NULL,
  PRIMARY KEY (`id_médico_procedimiento`, `tb_procedimiento_id_procedimiento`, `tb_médico_id_médico`),
  INDEX `fk_médico_procedimiento_tb_procedimiento1_idx` (`tb_procedimiento_id_procedimiento` ASC) VISIBLE,
  INDEX `fk_médico_procedimiento_tb_médico1_idx` (`tb_médico_id_médico` ASC) VISIBLE,
  CONSTRAINT `fk_médico_procedimiento_tb_procedimiento1`
    FOREIGN KEY (`tb_procedimiento_id_procedimiento`)
    REFERENCES `hospital_db`.`tb_procedimiento` (`id_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_médico_procedimiento_tb_médico1`
    FOREIGN KEY (`tb_médico_id_médico`)
    REFERENCES `hospital_db`.`tb_médico` (`id_médico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`tb_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`tb_medicamento` (
  `id_medicamento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dósis` DECIMAL(6,1) NOT NULL,
  PRIMARY KEY (`id_medicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`paciente_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`paciente_medicamento` (
  `id_paciente_medicamento` INT NOT NULL,
  `tb_medicamento_id_medicamento` INT NOT NULL,
  `tb_paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_paciente_medicamento`, `tb_medicamento_id_medicamento`, `tb_paciente_id_paciente`),
  INDEX `fk_paciente_medicamento_tb_medicamento1_idx` (`tb_medicamento_id_medicamento` ASC) VISIBLE,
  INDEX `fk_paciente_medicamento_tb_paciente1_idx` (`tb_paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_medicamento_tb_medicamento1`
    FOREIGN KEY (`tb_medicamento_id_medicamento`)
    REFERENCES `hospital_db`.`tb_medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_medicamento_tb_paciente1`
    FOREIGN KEY (`tb_paciente_id_paciente`)
    REFERENCES `hospital_db`.`tb_paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`teléfono_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`teléfono_paciente` (
  `teléfono` INT NOT NULL,
  `tb_paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`tb_paciente_id_paciente`),
  CONSTRAINT `fk_teléfono_paciente_tb_paciente1`
    FOREIGN KEY (`tb_paciente_id_paciente`)
    REFERENCES `hospital_db`.`tb_paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_db`.`teléfono_médico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`teléfono_médico` (
  `teléfono` INT NOT NULL,
  `tb_médico_id_médico` INT NOT NULL,
  PRIMARY KEY (`tb_médico_id_médico`),
  CONSTRAINT `fk_teléfono_médico_tb_médico1`
    FOREIGN KEY (`tb_médico_id_médico`)
    REFERENCES `hospital_db`.`tb_médico` (`id_médico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
